/**
* This file is autogenerated by nRFgo Studio 1.21.2RC1.4
*/

#include "services.h"
#include "lib_aci.h"

static bool is_ambient_light_sensor_sequence_number_send_requested = false;
static bool is_ambient_light_sensor_sequence_number_ack_send_requested = false;
static bool is_ambient_light_sensor_sequence_number_set_requested = false;
static bool is_ambient_light_sensor_device_name_send_requested = false;
static bool is_ambient_light_sensor_device_name_ack_send_requested = false;
static bool is_ambient_light_sensor_device_name_set_requested = false;
static bool is_ambient_light_sensor_ambient_light_measurement_send_requested = false;
static bool is_ambient_light_sensor_ambient_light_measurement_ack_send_requested = false;
static bool is_ambient_light_sensor_ambient_light_measurement_set_requested = false;

static uint8_t ambient_light_sensor_sequence_number_tx;
static uint8_t ambient_light_sensor_sequence_number_tx_ack;
static uint8_t ambient_light_sensor_sequence_number_set;
static void *ambient_light_sensor_device_name_tx;
static uint8_t ambient_light_sensor_device_name_tx_size;
static void *ambient_light_sensor_device_name_tx_ack;
static uint8_t ambient_light_sensor_device_name_tx_ack_size;
static void *ambient_light_sensor_device_name_set;
static uint8_t ambient_light_sensor_device_name_set_size;
static void *ambient_light_sensor_ambient_light_measurement_tx;
static uint8_t ambient_light_sensor_ambient_light_measurement_tx_size;
static void *ambient_light_sensor_ambient_light_measurement_tx_ack;
static uint8_t ambient_light_sensor_ambient_light_measurement_tx_ack_size;
static void *ambient_light_sensor_ambient_light_measurement_set;
static uint8_t ambient_light_sensor_ambient_light_measurement_set_size;

static bool ambient_light_sensor_sequence_number_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_AMBIENT_LIGHT_SENSOR_SEQUENCE_NUMBER_TX))
  {
    return(lib_aci_send_data(PIPE_AMBIENT_LIGHT_SENSOR_SEQUENCE_NUMBER_TX, (void*)&ambient_light_sensor_sequence_number_tx, 1));
  }
  return(false);
}

bool services_send_ambient_light_sensor_sequence_number(uint8_t src, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ambient_light_sensor_sequence_number_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ambient_light_sensor_sequence_number_send_requested)
    {
      ambient_light_sensor_sequence_number_tx = src;
      is_ambient_light_sensor_sequence_number_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ambient_light_sensor_sequence_number_tx = src;
    is_ambient_light_sensor_sequence_number_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ambient_light_sensor_sequence_number_update_send_ack(void)
{
  if (lib_aci_is_pipe_available(PIPE_AMBIENT_LIGHT_SENSOR_SEQUENCE_NUMBER_TX_ACK))
  {
    return(lib_aci_send_data(PIPE_AMBIENT_LIGHT_SENSOR_SEQUENCE_NUMBER_TX_ACK, (void*)&ambient_light_sensor_sequence_number_tx_ack, 1));
  }
  return(false);
}

bool services_send_ambient_light_sensor_sequence_number_ack(uint8_t src, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ambient_light_sensor_sequence_number_ack_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ambient_light_sensor_sequence_number_ack_send_requested)
    {
      ambient_light_sensor_sequence_number_tx_ack = src;
      is_ambient_light_sensor_sequence_number_ack_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ambient_light_sensor_sequence_number_tx_ack = src;
    is_ambient_light_sensor_sequence_number_ack_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ambient_light_sensor_sequence_number_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_AMBIENT_LIGHT_SENSOR_SEQUENCE_NUMBER_SET, (void*)&ambient_light_sensor_sequence_number_set, 1));
}

void services_set_ambient_light_sensor_sequence_number(uint8_t src)
{
  ambient_light_sensor_sequence_number_set = src;
  is_ambient_light_sensor_sequence_number_set_requested = true;
  services_update_pipes();
}
static bool ambient_light_sensor_device_name_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_AMBIENT_LIGHT_SENSOR_DEVICE_NAME_TX))
  {
    return(lib_aci_send_data(PIPE_AMBIENT_LIGHT_SENSOR_DEVICE_NAME_TX, (void*)ambient_light_sensor_device_name_tx, ambient_light_sensor_device_name_tx_size));
  }
  return(false);
}

bool services_send_ambient_light_sensor_device_name(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ambient_light_sensor_device_name_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ambient_light_sensor_device_name_send_requested)
    {
      ambient_light_sensor_device_name_tx_size = size;
      ambient_light_sensor_device_name_tx = src;
      is_ambient_light_sensor_device_name_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ambient_light_sensor_device_name_tx_size = size;
    ambient_light_sensor_device_name_tx = src;
    is_ambient_light_sensor_device_name_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ambient_light_sensor_device_name_update_send_ack(void)
{
  if (lib_aci_is_pipe_available(PIPE_AMBIENT_LIGHT_SENSOR_DEVICE_NAME_TX_ACK))
  {
    return(lib_aci_send_data(PIPE_AMBIENT_LIGHT_SENSOR_DEVICE_NAME_TX_ACK, (void*)ambient_light_sensor_device_name_tx_ack, ambient_light_sensor_device_name_tx_ack_size));
  }
  return(false);
}

bool services_send_ambient_light_sensor_device_name_ack(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ambient_light_sensor_device_name_ack_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ambient_light_sensor_device_name_ack_send_requested)
    {
      ambient_light_sensor_device_name_tx_ack_size = size;
      ambient_light_sensor_device_name_tx_ack = src;
      is_ambient_light_sensor_device_name_ack_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ambient_light_sensor_device_name_tx_ack_size = size;
    ambient_light_sensor_device_name_tx_ack = src;
    is_ambient_light_sensor_device_name_ack_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ambient_light_sensor_device_name_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_AMBIENT_LIGHT_SENSOR_DEVICE_NAME_SET, (void*)ambient_light_sensor_device_name_set, ambient_light_sensor_device_name_set_size));
}

void services_set_ambient_light_sensor_device_name(void *src, int size)
{
  ambient_light_sensor_device_name_set_size = size;
  ambient_light_sensor_device_name_set = src;
  is_ambient_light_sensor_device_name_set_requested = true;
  services_update_pipes();
}
static bool ambient_light_sensor_ambient_light_measurement_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_AMBIENT_LIGHT_SENSOR_AMBIENT_LIGHT_MEASUREMENT_TX))
  {
    return(lib_aci_send_data(PIPE_AMBIENT_LIGHT_SENSOR_AMBIENT_LIGHT_MEASUREMENT_TX, (void*)ambient_light_sensor_ambient_light_measurement_tx, ambient_light_sensor_ambient_light_measurement_tx_size));
  }
  return(false);
}

bool services_send_ambient_light_sensor_ambient_light_measurement(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ambient_light_sensor_ambient_light_measurement_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ambient_light_sensor_ambient_light_measurement_send_requested)
    {
      ambient_light_sensor_ambient_light_measurement_tx_size = size;
      ambient_light_sensor_ambient_light_measurement_tx = src;
      is_ambient_light_sensor_ambient_light_measurement_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ambient_light_sensor_ambient_light_measurement_tx_size = size;
    ambient_light_sensor_ambient_light_measurement_tx = src;
    is_ambient_light_sensor_ambient_light_measurement_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ambient_light_sensor_ambient_light_measurement_update_send_ack(void)
{
  if (lib_aci_is_pipe_available(PIPE_AMBIENT_LIGHT_SENSOR_AMBIENT_LIGHT_MEASUREMENT_TX_ACK))
  {
    return(lib_aci_send_data(PIPE_AMBIENT_LIGHT_SENSOR_AMBIENT_LIGHT_MEASUREMENT_TX_ACK, (void*)ambient_light_sensor_ambient_light_measurement_tx_ack, ambient_light_sensor_ambient_light_measurement_tx_ack_size));
  }
  return(false);
}

bool services_send_ambient_light_sensor_ambient_light_measurement_ack(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ambient_light_sensor_ambient_light_measurement_ack_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ambient_light_sensor_ambient_light_measurement_ack_send_requested)
    {
      ambient_light_sensor_ambient_light_measurement_tx_ack_size = size;
      ambient_light_sensor_ambient_light_measurement_tx_ack = src;
      is_ambient_light_sensor_ambient_light_measurement_ack_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ambient_light_sensor_ambient_light_measurement_tx_ack_size = size;
    ambient_light_sensor_ambient_light_measurement_tx_ack = src;
    is_ambient_light_sensor_ambient_light_measurement_ack_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ambient_light_sensor_ambient_light_measurement_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_AMBIENT_LIGHT_SENSOR_AMBIENT_LIGHT_MEASUREMENT_SET, (void*)ambient_light_sensor_ambient_light_measurement_set, ambient_light_sensor_ambient_light_measurement_set_size));
}

void services_set_ambient_light_sensor_ambient_light_measurement(void *src, int size)
{
  ambient_light_sensor_ambient_light_measurement_set_size = size;
  ambient_light_sensor_ambient_light_measurement_set = src;
  is_ambient_light_sensor_ambient_light_measurement_set_requested = true;
  services_update_pipes();
}

void services_update_pipes(void)
{
  if(is_ambient_light_sensor_sequence_number_send_requested)
  {
    is_ambient_light_sensor_sequence_number_send_requested = !(ambient_light_sensor_sequence_number_update_send());
  }
  if(is_ambient_light_sensor_sequence_number_ack_send_requested)
  {
    is_ambient_light_sensor_sequence_number_ack_send_requested = !(ambient_light_sensor_sequence_number_update_send_ack());
  }
  if(is_ambient_light_sensor_sequence_number_set_requested)
  {
    is_ambient_light_sensor_sequence_number_set_requested = !(ambient_light_sensor_sequence_number_update_set());
  }
  if(is_ambient_light_sensor_device_name_send_requested)
  {
    is_ambient_light_sensor_device_name_send_requested = !(ambient_light_sensor_device_name_update_send());
  }
  if(is_ambient_light_sensor_device_name_ack_send_requested)
  {
    is_ambient_light_sensor_device_name_ack_send_requested = !(ambient_light_sensor_device_name_update_send_ack());
  }
  if(is_ambient_light_sensor_device_name_set_requested)
  {
    is_ambient_light_sensor_device_name_set_requested = !(ambient_light_sensor_device_name_update_set());
  }
  if(is_ambient_light_sensor_ambient_light_measurement_send_requested)
  {
    is_ambient_light_sensor_ambient_light_measurement_send_requested = !(ambient_light_sensor_ambient_light_measurement_update_send());
  }
  if(is_ambient_light_sensor_ambient_light_measurement_ack_send_requested)
  {
    is_ambient_light_sensor_ambient_light_measurement_ack_send_requested = !(ambient_light_sensor_ambient_light_measurement_update_send_ack());
  }
  if(is_ambient_light_sensor_ambient_light_measurement_set_requested)
  {
    is_ambient_light_sensor_ambient_light_measurement_set_requested = !(ambient_light_sensor_ambient_light_measurement_update_set());
  }
}

